
package uy.turismo.webapp.ws.controller;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PublisherService", targetNamespace = "controller", wsdlLocation = "file:/home/prog-app/Documentos/GitHub/Prog-App-23/src/main/resources/publisher.wsdl")
public class PublisherService
    extends Service
{

    private final static URL PUBLISHERSERVICE_WSDL_LOCATION;
    private final static WebServiceException PUBLISHERSERVICE_EXCEPTION;
    private final static QName PUBLISHERSERVICE_QNAME = new QName("controller", "PublisherService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/prog-app/Documentos/GitHub/Prog-App-23/src/main/resources/publisher.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PUBLISHERSERVICE_WSDL_LOCATION = url;
        PUBLISHERSERVICE_EXCEPTION = e;
    }

    public PublisherService() {
        super(__getWsdlLocation(), PUBLISHERSERVICE_QNAME);
    }

    public PublisherService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PUBLISHERSERVICE_QNAME, features);
    }

    public PublisherService(URL wsdlLocation) {
        super(wsdlLocation, PUBLISHERSERVICE_QNAME);
    }

    public PublisherService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PUBLISHERSERVICE_QNAME, features);
    }

    public PublisherService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PublisherService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Publisher
     */
    @WebEndpoint(name = "PublisherPort")
    public Publisher getPublisherPort() {
        return super.getPort(new QName("controller", "PublisherPort"), Publisher.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Publisher
     */
    @WebEndpoint(name = "PublisherPort")
    public Publisher getPublisherPort(WebServiceFeature... features) {
        return super.getPort(new QName("controller", "PublisherPort"), Publisher.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PUBLISHERSERVICE_EXCEPTION!= null) {
            throw PUBLISHERSERVICE_EXCEPTION;
        }
        return PUBLISHERSERVICE_WSDL_LOCATION;
    }

}
